# Generated by Django 5.2.2 on 2025-06-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('instructor', models.CharField(max_length=100)),
                ('available_slots', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
