# Generated by Django 5.2.2 on 2025-06-06 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitness', '0002_delete_fitnessclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('datetime_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('instructor', models.CharField(max_length=100)),
                ('available_slots', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
