# Generated by Django 5.2.2 on 2025-06-06 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('datetime_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.CharField(blank=True, max_length=50, null=True)),
                ('fitness_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_booking', to='fitness.fitnessclass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
